INSERT INTO coupon (type, discount_details, conditioning, isActive, code) VALUES
('BxGy', '{"buyIds": [3, 4, 5], "getIds": [6, 7, 8], "maxRedemption": 1}', '{"buy": 1, "get": 1}', '1', 'BXGY_3_4_5'),
('BxGy', '{"buyIds": [1, 3, 5], "getIds": [2, 4, 6], "maxRedemption": 3}', '{"buy": 3, "get": 2}', '1', 'BXGY_1_3_5'),
('BxGy', '{"buyIds": [4, 5, 6, 7], "getIds": [8, 9, 10, 11], "maxRedemption": 4}', '{"buy": 4, "get": 3}', '1', 'BXGY_4_5_6_7'),
('BxGy', '{"buyIds": [5, 6, 7, 8], "getIds": [9, 10, 11, 12], "maxRedemption": 2}', '{"buy": 2, "get": 1}', '1', 'BXGY_5_6_7_8'),
('cart-wise', '{"type": "percentage", "value": 30, "discountAmountMax": "150"}', '{"minCartValue": 300}', '1', 'CART300'),
('cart-wise', '{"type": "percentage", "value": 5, "discountAmountMax": "25"}', '{"minCartValue": 50}', '1', 'CART50'),
('cart-wise', '{"type": "percentage", "value": 23, "discountAmountMax": "115"}', '{"minCartValue": 230}', '1', 'CART230'),
('cart-wise', '{"type": "percentage", "value": 50, "discountAmountMax": "500"}', '{"minCartValue": 1000}', '0', 'CART1000'),
('product-wise', '{"type": "percentage", "value": 30, "discountAmountMax": "250"}', '{"productIds": [2, 3, 4]}', '1', 'PROD_2_3_4'),
('product-wise', '{"type": "percentage", "value": 24, "discountAmountMax": "190"}', '{"productIds": [1, 2, 3, 4]}', '1', 'PROD_1_2_3_4'),
('product-wise', '{"type": "percentage", "value": 40, "discountAmountMax": "350"}', '{"productIds": [1, 3, 5]}', '1', 'PROD_1_3_5'),
('product-wise', '{"type": "percentage", "value": 45, "discountAmountMax": "400"}', '{"productIds": [1, 2, 3, 4, 5]}', '0', 'PROD_1_2_3_4_5'),
('cart-wise', '{"type": "percentage", "value": 13, "discountAmountMax": "65"}', '{"minCartValue": 130}', '1', 'CART130'),
('product-wise', '{"type": "percentage", "value": 22, "discountAmountMax": "175"}', '{"productIds": [2, 4, 6]}', '1', 'PROD_2_4_6'),
('BxGy', '{"buyIds": [3, 4], "getIds": [5, 6], "maxRedemption": 1}', '{"buy": 1, "get": 1}', '1', 'BXGY_3_4'),
('cart-wise', '{"type": "percentage", "value": 28, "discountAmountMax": "140"}', '{"minCartValue": 280}', '1', 'CART280'),
('product-wise', '{"type": "percentage", "value": 29, "discountAmountMax": "240"}', '{"productIds": [2, 3, 4, 5]}', '1', 'PROD_2_3_4_5'),
('BxGy', '{"buyIds": [1, 2, 3], "getIds": [4, 5, 6], "maxRedemption": 4}', '{"buy": 4, "get": 3}', '1', 'BXGY_1_2_3'),
('product-wise', '{"type": "percentage", "value": 35, "discountAmountMax": "300"}', '{"productIds": [2, 4, 6, 8, 10]}', '0', 'PROD_2_4_6_8_10'),
('cart-wise', '{"type": "percentage", "value": 17, "discountAmountMax": "85"}', '{"minCartValue": 170}', '1', 'CART170');